# Read nord.css and extract just the lines with variable definitions
lines <- readLines(file.path("lib", "nord.css"))
lines <- trimws(lines[grep("--nord", lines)])

# Split lines into vectors of names and RGB values, respectively
tmp <- strsplit(lines, "\\s+", perl = TRUE)
varnames <- gsub("nord", "nrgb", vapply(tmp, `[`, "", i = 1))
varvals <- apply(col2rgb(gsub(";", "", vapply(tmp, `[`, "", i = 2))),
                 2, paste, collapse = ",")

# Write new CSS file
css <- c("/* This file is autogenerated by `generate-css.R` */\n",
         ":root {", paste0("    ", varnames, varvals, ";"), "}")
cat(css, file = file.path("gen", "nord-rgb.css"), sep = "\n")
